### ISSUE TITLE
Wifi not connecting on 5.3 OS

### ISSUE THREAD

**Issue by bcarriveau** [FalconChristmas/fpp#1139]
Just spent a bit more then a hour helping a guy setup a new K8-B , wifi adapter from Dan the 1200MBS adapter , no matter what we tried, renamed ssids, changed passwords , reimaged.  Tried this all on 5.3 AND 5.3.1, no such luck. Asus Router. 

installed 5.2 and upgraded to 5.3.1 on a 5.0 OS and all works just fine. Tether worked just fine.

i know this is much info but we have seen alot of wifi issues in the last few days with 5.3 os.

**Comment by FarmallDude** [comment]
> > Having the same issue. Flashed fresh 5.3.1 image on F8-PB. Tethered via USB to configure network. Updated, rebooted, but I cannot connect. I can see the FPP on my network so I know it's connected, and the light on the WiFi dongle is showing activity, AND the F8-PB display is showing the correct IP address. I'm stumped. NOTE: I even tried down-grading to 4.6.1 as I think that's the version I used last year. But, I'm getting the same issue with it too.
> 
> we couldn't connect at all unless wired, but installing a 5.2fppos to bring the OS back to 5.0 seemed to be the only fix at this point for him.

OK, so can someone point me to the instructions on how to install the fppos? Just tried flashing it with Etcher, but it doesn't have a partition table (not bootable). I'll snoop around too, maybe I'll stumble upon it. :)

**Comment by bcarriveau** [comment]
> > > Having the same issue. Flashed fresh 5.3.1 image on F8-PB. Tethered via USB to configure network. Updated, rebooted, but I cannot connect. I can see the FPP on my network so I know it's connected, and the light on the WiFi dongle is showing activity, AND the F8-PB display is showing the correct IP address. I'm stumped. NOTE: I even tried down-grading to 4.6.1 as I think that's the version I used last year. But, I'm getting the same issue with it too.
> > 
> > 
> > we couldn't connect at all unless wired, but installing a 5.2fppos to bring the OS back to 5.0 seemed to be the only fix at this point for him.
> 
> OK, so can someone point me to the instructions on how to install the fppos? Just tried flashing it with Etcher, but it doesn't have a partition table (not bootable). I'll snoop around too, maybe I'll stumble upon it. :)

the fppos is an Inplace upgrade, if you want to image, get the 5.2 img file and burn that. you can then do the normal updates and it will bring you to 5.3.1 and stay on the 5.0 OS witch seems to be less problematic at this point. Had another in zoom needing to go back tonight aswell.

**Comment by FarmallDude** [comment]
Thanks bcarriveau.
I did figure out how to do the OS upgrade in the Release instructions. I tried it but no joy for me. I even flashed way back to version 3.6.2 (or 3.2.1?) Anyway, still no connection over WiFi. I can still see it on my router and the dongle is flickering showing activity, but my PC just won't connect to it. I need to rule out 3 possibilities: 1-Hardware. How can I validate the WiFi dongle is actually working? 2-Board Software. I believe this is working fine since I can tether via USB with no problem. 3-PC OS issue. Is it possible our friends at Microsoft have caused the problem? Are there any Windows 10 Pro 21H1 build 19043.1288 Feature Pack 120.2212.3920.0 configurations that I need to do?

**Comment by FarmallDude** [comment]
I discovered if my PC is hardwired (ethernet) to my network I can connect to my P8-PB wirelessly, but only from FireFox on a Ubuntu laptop. BUT, when I boot the controller, I have to unplug the WiFi adapter, wait 10 seconds then plug it back in before it gets an IP address. Weird, huh?

**Comment by bcarriveau** [comment]
I was traveling when I messed with it last but it appeared to sometimes get a nice status light on the dongle. Other times it would flash one flash every once in a while if I recall.

**Comment by bloojoop** [comment]
I have been able to replicate this issue on a K8-B.  When running FPP 5.3.1 with OS 5.0, I can have eth0 and wlan0 connected both at the same time, no issue.  With OS 5.3, and with the eth0 plugged in, I cannot get the wlan0 to join my SSID.  When I unplug eth0, the wlan0 connects immediately.  When I plug in eth0, it will configure and show both until the next reboot.  Then after reboot, only eth0 will connect and wlan0 will NOT connect.  in OS 5.3 I cannot get both connected at the same time.  I am attaching a image of my SD card.  I reduced the partition to 6GB and captured it to save space. 

The file seems to not want to attach here so here is a link to in on my google drive. https://drive.google.com/file/d/1AZg2bx2qQBCI8D_mIKtdzXMHWQa3d_Qk/view?usp=sharing

**Comment by jlange6648** [comment]
Seeing the same behavior as @bloojoop...
1) Boot without Ethernet, wifi comes up.
2) Plug in Ethernet, both are working.
3) Reboot, no wifi

**Comment by jlange6648** [comment]
Verified that after applying the connman config change made in https://github.com/FalconChristmas/fpp/commit/4ff0d1c10b21f7a0f905dd771043d95292f23c56 The issue is resolved.

**Comment by bloojoop** [comment]
I switched two of my devices to master branch and can confirm in my case this issue is resolved with the update.

**Comment by ghormann** [comment]
If others are still having problems, suggest switching to version 5.4 which includes this fix.
