### ISSUE TITLE
FPP Docker problem with Raspberry PI 4 armv 7

### ISSUE THREAD

**Issue by bakelitephone** [FalconChristmas/fpp#1272]
Hi I am trying to install FPP as a docker container on a Raspberry PI 4 however I get the following error message:

sudo docker pull falconchristmas/fpp
_Using default tag: latest
latest: Pulling from falconchristmas/fpp
**no matching manifest for linux/arm/v7 in the manifest list entries**_

I have tried both image: falconchristmas/fpp and image: falconchristmas/fpp:latest

My environment is a Raspberry PI 4 with 4GB Mem + 240GM SSD

_**Debian 32bit**
Distributor ID:	Raspbian
Description:	**Raspbian GNU/Linux 11 (bullseye)**
Release:	11
Codename:	bullseye_

sudo docker version
Client: Docker Engine - Community
 **Version:           20.10.14**
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:48:46 2022
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:46:45 2022
  **OS/Arch:          linux/arm**
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by ghormann** [comment]
Historically we have only build build 64 bit images.  (Specifically linux/amd64 and linux/arm64. )  You appear to be using a 32-bit kernel.   I just pushed a change to build linux/arm/v7 build I don't have a good way to test it.

**Comment by bakelitephone** [comment]
> Historically we have only build build 64 bit images. (Specifically linux/amd64 and linux/arm64. ) You appear to be using a 32-bit kernel. I just pushed a change to build linux/arm/v7 build I don't have a good way to test it.

Thanks! Rookie mistake on my part, MANY thanks for the quick response. 
FYI:  I still get the same error 
_sudo docker pull falconchristmas/fpp
Using default tag: latest
latest: Pulling from falconchristmas/fpp
no matching manifest for linux/arm/v7 in the manifest list entries_

Its not a problem now I know I will rebuild my Raspberry PI 4 with a 64 bit debian raspbian base image and then load Open Media Vault etc as I like to use "Portainer Stacks" (Docker compose) for all my Docker containers.

PS Your Docker Compose script is really well commented, one of the best I have seen :-)

Thanks again and keep up the good work with the fpp Docker containers. I have used them on a small Intel NUC machine when I could not buy a PI however I love Docker compose as it makes my life so much easier (rebuilding systems etc), especially as I ran 12 other containers on the same NUC (saves on hardware space/costs and power consumption).

**Comment by ghormann** [comment]
It is still building.  https://github.com/FalconChristmas/fpp/runs/6146544880?check_suite_focus=true

**Comment by ghormann** [comment]
It has been published
![image](https://user-images.githubusercontent.com/24968726/164981386-98987f73-f9a0-4538-8abb-a7d52858051c.png)

**Comment by bakelitephone** [comment]
Apologies I can't test the 32 bit image as I jumped the gun and rebuilt my PI 4 with 64 bit Raspbian.

I can confirm the 64 bit docker image pulls OK and the stack (docker compose) ran fine on the PI with just a couple of minor tweaks.

I now have an OMV (Open Media Vault) 240GB SSD NAS on my raspberry PI 4 running portainer and a first container of fpp that appears to work fine (see screenshot). :-) :-) :-) No more worrying about potential SD card failures....

Thanks for your help and I am sure someone else will make the same mistake I did and try to build on top of the standard 32 bit Raspbian base, so your proactive 32 bit Docker build will not go to waste.

Again please keep up the Docker work as I am sure newbies like me will use it more and more as they discover how stable/useful and easy it really is :-)
 
![97526913-0F91-4355-BA6E-0454B2CAF35E](https://user-images.githubusercontent.com/69304144/164981901-22cbc0db-feee-4927-b11b-c4e2f4c6ec18.jpeg)
