### ISSUE TITLE
FPP V8: Storage Device dropdown is not populationg with the current storage setting.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1871]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
**FPP Version and Hardware**: 
*FPP Alpha 5 -v8.x-master-324-g66745d8c on a Pi5 but also appears on Pi4*

**Describe the bug and Steps to reproduce**: 
Go to FPP Settings - Storage tab
Look at Storage Device
If defaulting to the first one on the list, it's not displaying the current storage setting. This works fine in V7.
I suspect it has to do with the new bootstrap code?

**Expected behavior**: 
I believe that is should show the curretnly configured storage device
**Additional Attachments**
**7.5**
![image](https://github.com/FalconChristmas/fpp/assets/8147459/4ac5b1d4-a7a9-4b23-87cc-ad4cda22afd0)

**8,x**
![image](https://github.com/FalconChristmas/fpp/assets/8147459/6b32d7a1-724b-4735-b122-10a13f174161)

**Comment by darylc** [comment]
@OnlineDynamic do you want to check this one out?

**Comment by OnlineDynamic** [comment]
@patdelaney think I have fixed in latest releases can you please double check - it wasn't bootstrap related - it was an issue with logic to determine the storage device - I have also fixed so only the partition with the boot code is marked as the boot device 
![image](https://github.com/user-attachments/assets/609d6de9-022c-4e0a-90c1-ffc3db9942c5)

**Comment by darylc** [comment]
closed due to no response

**Comment by patdelaney** [comment]
This still appears to be an issue:
On a Pi5 with nvme device, the list is sorted alphbetically.
![image](https://github.com/user-attachments/assets/159b7641-f3d8-4d73-85ec-349dd4628eca)

It appears to be OK on BBB platform, but I have not tested when BBB boots from EMMC storage.

On Pi 4 it's displaying alphabetically again and not displaying to current storage page in the box>
![image](https://github.com/user-attachments/assets/950fef3f-34e8-40e6-939e-39fe7e278d9c)

**Comment by OnlineDynamic** [comment]
@patdelaney I'll have a look when I'm back in dev mode on Sunday... is it correctly defaulting to the entry marked in brackets as the "current storage device" even if it isn't at the top of the list?

**Comment by patdelaney** [comment]
Yes, it identified the correct device, it's just not at the top of the list

**Comment by OnlineDynamic** [comment]
@patdelaney - hi started to look at this... bit confused what you want it to do... when I load the page I see:
![image](https://github.com/user-attachments/assets/3ebc8ca1-1f23-43f6-8e33-d3d60f40b253) 
with it defaulting to show the current storage device... if I expand the dropdown they are in alphabetical order:
![image](https://github.com/user-attachments/assets/6a1fcfd8-dd51-433b-84cb-8bc8514c2af5)
do you want to have the storage devices in a different order? Current at top and then rest alphabetical?

**Comment by patdelaney** [comment]
the box is showing the first thing in the list and the list is alphabetized. The sorage device was being displayed as the default>
![image](https://github.com/user-attachments/assets/78694dac-e286-4f4d-aaf1-e97b9e0ce89d)

**Comment by OnlineDynamic** [comment]
@patdelaney - what browser are you using? - I've tried Edge, Chrome and firefox and they all load the "current storage device" entry as the default selected and the correct entry in the select options is marked as 'selected' in the generated html:

![image](https://github.com/user-attachments/assets/4471745c-844f-41f0-9c3f-d3e37a2fc610)

**Comment by patdelaney** [comment]
Chrome

**Comment by OnlineDynamic** [comment]
perhaps we can have a quick call on this one so I can understand and try to recreate the issue on my side

**Comment by darylc** [comment]
replicated @patdelaney's problem on my dev pi (with nvme) and fixed it.
