### ISSUE TITLE
No channels on channel output page BBB16, FPPV8.

### ISSUE THREAD

**Issue by rayhjr** [FalconChristmas/fpp#1964]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**:FPP 8.0 running on BBB16
Example: *FPP 4.2 running on BBB*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
2. Click on 'output tab....'
4. See error See only red tad at top left of page, nothing else, no channels or tabs at bottom of page

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.
Expect to see channels
**Additional context**: 
I have tried updating to v8. fresh flash of  v8 several times and on multiple boards.
During a attempt to upgrade eeprom I got a error message that one or more outputs were set up for more than 50 pixels
even though output page is blank. Going back to FPP7.5 and outputs are there.
 
**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

[FPP_Logs_20240907.1548.zip](https://github.com/user-attachments/files/16918962/FPP_Logs_20240907.1548.zip)
![no outputs](https://github.com/user-attachments/assets/cc1944dd-6083-425b-a0ff-0987d2621cbe)
![warning](https://github.com/user-attachments/assets/7c486475-91c9-42da-86f8-ef1d654182ad)
Thanks for all your help!

**Comment by rayhjr** [comment]
I did get FPPv8 to work properly on a wireless BBB I have the files for it.
[FPP_Logs_20240808.0003.zip](https://github.com/user-attachments/files/16923309/FPP_Logs_20240808.0003.zip)

**Comment by dkulp** [comment]
Fixed on master

**Comment by rayhjr** [comment]
Hello Dan. I appreciate you taking time to look at this, but I still don't see output channels.  I did an upgrade and a new image but neither way has channels. well new image and upgrade. Just curious what you saw in my files and what I'm doing wrong? Thanks, Ray.
________________________________

**Comment by cybercop23** [comment]
Are you on the master branch? It wasn't fixed in 7.5 or 8.. it was fixed on the master branch... you can change to the master branch if you want. Status Control -? FPP Settings -> Developer (may need to change UI to Advanced or even Developer) and change branch to master.
![image](https://github.com/user-attachments/assets/4fa9a800-697d-4e06-acd8-6a81ad91b794)

**Comment by rayhjr** [comment]
Ok, I'm sorry. I did not understand. Thanks again.
