### ISSUE TITLE
9.x-master - Pixel Stings and RPIWS281x Errors

### ISSUE THREAD

**Issue by bobreese** [FalconChristmas/fpp#2237]
Enabling or Disabling Pixel Stings and Saving causes the Pi to reboot.
Also, enabling Pixel Stings causes a RPIWS281x Abnormal Conditions - May cause poor performance or other issues
 RPIWS281x: ws2811_init() failed. Error code: -3
 Could not initialize output type RPIWS281X. Check logs for details.

![Image](https://github.com/user-attachments/assets/72d04c3e-6e39-446d-a68f-a97f0a75b813)

[FPP_Pi5_Logs_20250531.1609.zip](https://github.com/user-attachments/files/20534983/FPP_Pi5_Logs_20250531.1609.zip)

**Comment by dkulp** [comment]
This is normal on the Pi5.   The "PiHat" configuration cannot be used on a Pi 5.  You can select the PiHat-DPIPixels config type and that will work.  

I've updated the code to not allow the PiHat option when running on a Pi5.

**Comment by bobreese** [comment]
I ran the update on my Pi 5 and it did set the output to PiHat-DPIPixels.
I have a soundblaster connected and setup as the Audio device.
I am Still getting the RPIWS281x: ws2811_init() failed. Error code: -3
Could not initialize output type RPIWS281X. Check logs for details.

**Comment by patdelaney** [comment]
If I am not mistaken the fix for this will be in the next kernel release. If you want to manually make a change you can ssh into the PI and paste the following:   then reboot

sudo PRUNE_MODULES=1 WANT_PI5=1 rpi-update
KV=$(uname -r)
KV=${KV::-3}

sudo rm -f /boot/*-${KV}*
sudo rm -rf /lib/modules/${KV}*
sudo rm -rf /usr/lib/linux-image-${KV}*
sudo rm -rf /boot/firmware/kernel_2712.img
sudo rm -rf /lib/modules/*-16K*

**Comment by bobreese** [comment]
Thank you, that seems to have worked.
