### ISSUE TITLE
Setting Configuration on First Boot Up

### ISSUE THREAD

**Issue by thekameleon** [FalconChristmas/fpp#2339]
**Is your feature request related to a problem? Please describe.**
It's an inconvenience.

**Describe the solution you'd like**
After I image FPP onto a MicroSD card.  Would it be possible to take a JSON backup configuration stick onto the image. And have FPP automatically apply the configuration? 

**Describe alternatives you've considered**
Manually doing it like we always have

**Additional context**
One scenario is upgrading a K32A-B to K32 Max.  My configuration doesn't change, just the board. Another would be mass configuring boards.

**Comment by dkulp** [comment]
There is some ability to do similar things for the Pi and BB64 images.    If there is a script called "fpp_boot.sh" in the FAT partition, that will be executed at boot.  Thus, you can pretty much do all kinds of things from the script.   Also, if there is a "fpp" dir there, anything in there will be copied into /home/fpp/media (cp -a  so full traversal).    Thus, you can setup the FAT drive for some of this.

That said, it's not really well known as it's never been usable for the Beagles as the Beagles don't have the FAT partition.   Supposedly, that may change for Trixie, but I haven't dug into that enough yet.

**Comment by jessica12ryan** [comment]
Does anyone have any objections to this? I have it ready to commit and send through a PR if we are in agreement with it.

https://github.com/user-attachments/assets/3e9b280b-5218-4f8b-9034-4ec401434c47

**Comment by cybercop23** [comment]
That's pretty handy. How will this work/look on a mobile phone?

**Comment by dkulp** [comment]
My only objection is have it at the very top like that taking up a ton of space by default.....   90% of the time (or more) it won't be used so having it up there like that is a big issue.  Maybe a button under the "Finish Setup" for "Restore from Backup" that would expose it or something.

**Comment by jessica12ryan** [comment]
https://github.com/user-attachments/assets/dbcae739-693d-4d14-a8f6-68079b283b60

https://github.com/user-attachments/assets/3deeb532-0e4c-4180-ac48-c1dcd14845e8

**Comment by darylc** [comment]
@thekameleon Are you in a position to test this with the latest nightly image?

**Comment by thekameleon** [comment]
Sure. Ill do so this weekend.

**Comment by thekameleon** [comment]
Yes. I should be able to this week.

Yahoo Mail: Search, Organize, Conquer 
 
  On Fri, Jun 26, 2026 at 21:05, ***@***.***> wrote:   darylc left a comment (FalconChristmas/fpp#2339)
@thekameleon Are you in a position to test this with the latest nightly image?

**Comment by thekameleon** [comment]
Just tried it out and honestly. This exceeded my expectations. The interface is great. I tried it with one moving head and it did what I thought it would do.
Cosmetically, its ok, not aure if you want to get all 16 channels in one or two rows on the desktop and honestly to save space on a mobile device, I see nothing wrong with making  the sliders horizontal.


Yahoo Mail: Search, Organize, Conquer 
 
  On Fri, Jun 26, 2026 at 21:05, ***@***.***> wrote:   darylc left a comment (FalconChristmas/fpp#2339)
@thekameleon Are you in a position to test this with the latest nightly image?

**Comment by darylc** [comment]
@thekameleon I think your comments above are about some other issue?  Do you mind rechecking?

**Comment by thekameleon** [comment]
Sorry you are right. Ill check this tomorrow

**Comment by bobreese** [comment]
I tested this this morning. While it worked well, there are 3 minor issues.

Did not change anything, just clicked the Restore from Backup.
<img width="1937" height="949" alt="Image" src="https://github.com/user-attachments/assets/a7a34361-9e0c-4e25-a5b7-82d3c4a9d776" />

Next screen I clicked to browse, choose the most recent backup.
<img width="1970" height="432" alt="Image" src="https://github.com/user-attachments/assets/daf6e261-a407-4661-ba30-fe8b4fc7eb96" />

Verified the file upload on the left and clicked Upload & Restore
<img width="1965" height="466" alt="Image" src="https://github.com/user-attachments/assets/8ece8213-b5db-4e84-9e6d-abee896989cd" />

Once completed, Rebooted
<img width="1962" height="717" alt="Image" src="https://github.com/user-attachments/assets/3702a297-e0c6-4031-92aa-90396b43aa11" />

First issue after the reboot is that MQTT was Disconnected.
<img width="1966" height="427" alt="Image" src="https://github.com/user-attachments/assets/b760ab53-04b5-423f-91ec-b93d9a68df45" />

Checking Services, Enable Local MQTT Broker was enabled. I found that Disabling, wait a few seconds and re-enable it fixed the issue.

<img width="1966" height="873" alt="Image" src="https://github.com/user-attachments/assets/937643e7-e8cf-4bad-a904-37d4320cd9a2" />

Last (while Minor) is there might be a need for a Reference Message on the second screen to inform users of what Might Not Be restored such as Plugin's, sequences, video's, etc.....

<img width="1966" height="581" alt="Image" src="https://github.com/user-attachments/assets/3dbabe02-d9db-488d-8b7f-8ea0bc212d23" />

**Comment by jessica12ryan** [comment]
@darylc You can assign this to me

Just to recap:
Issue 1: Reboot flag when no changes are made
Issue 2: MQTT Disconnected until disable/enable
Issue 3: A message displayed to indicate files are not included with JSON backup

I'm working on fixes over the next couple days, as well as a couple enhancements.

**Comment by bobreese** [comment]
Tested this morning and the MQTT error does not appear.
All other functions appear to be working as expected.

**Comment by jessica12ryan** [comment]
Issue 2 and 3 from my last comment are resolved with my PR's. Issue 1 is an issue that was present outside of these changes. I've created a separate issue to detail my findings regarding it as it's not something I feel comfortable with approaching without further instruction from senior developers.

**Comment by darylc** [comment]
@jessica12ryan  I believe @bobreese said the mqtt thing is still broken, ig not lets close this one out

**Comment by jessica12ryan** [comment]
@darylc 
A fix was submitted for Bob's latest MQTT concerns (PR #2785) and I requested that Bob retest to confirm it is resolved in #2752.

@bobreese 
Can you retest the MQTT issue from #2752 and post your findings here? It should be resolved now! :)

**Comment by bobreese** [comment]
After a Restore from a Remote Backup, the MQTT errors are back.
I had to do one this morning and had to manually stop and start the service to clear the issue.

**Comment by jessica12ryan** [comment]
Okay, back to the drawing board.... I'll have to dust off a spare Pi and keep digging deeper into this. Perhaps by any chance, do you still have logs from that test?

**Comment by bobreese** [comment]
I will look... BTW: one thing I have not tried is restarting FPPD after the restore.... hmmmm
Added logs
[GPIOTest_Logs_20260731_1103.zip](https://github.com/user-attachments/files/30595773/GPIOTest_Logs_20260731_1103.zip)

**Comment by jessica12ryan** [comment]
That might be the issue. It should prompt you to restart fppd after a restore containing configuration files. That was put into one of the previous commits.

Thanks for the logs... I'm mobile right now but I'll pick through them soon.

**Comment by darylc** [comment]
@jessica12ryan Ran into Bob on zoom tonight and ssh'd into his pi to take a look at the result after a file copy backup.  Bob confirmed it works now.  I believe that was the last remaining thing in this issue, so closing it.
