### ISSUE TITLE
Dynamic playlist entry causes FPPD Daemon to crash

### ISSUE THREAD

**Issue by tomhammond** [FalconChristmas/fpp#2346]
[fpp-Pi-9.1-M1-0000000055f948e7-2025-09-01_20-31-58.zip](https://github.com/user-attachments/files/22085538/fpp-Pi-9.1-M1-0000000055f948e7-2025-09-01_20-31-58.zip)

Playlist:
![Image](https://github.com/user-attachments/assets/0a4664c9-f371-4fdc-8b04-a08d6838a5e1)

Status page fpp 9.1 error
![Image](https://github.com/user-attachments/assets/988fd727-0bcc-43e0-bbb0-2868f3a2f3c9)

Status page fpp 6.1.1 no error
![Image](https://github.com/user-attachments/assets/18ee7fe2-458a-42ea-a7f4-b275b51c03bf)

[test.json](https://github.com/user-attachments/files/22085546/test.json)

[FPP_all-backup_v9_unprotected_20250901211009.json](https://github.com/user-attachments/files/22085551/FPP_all-backup_v9_unprotected_20250901211009.json)

# Please answer the following:
FPP 9.1 on Raspberry Pi 2

Note: The following works fine on FPP 6.1.1, but crashes on FPP 9.1.  I fresh installed 9.1 on a different memory card, so I was able to compare the issue with 6.1.1 and 9.1. 

Steps:
I create a new playlist ("test-dynamic")
Add a Dynamic entry with a URL points to https://itwinkle.org/control-lights/test.json
Play the playlist from the Status page

Behavior:
The sequence begins to play, but the audio cuts out after a few seconds.  This is because the Daemon crashed.  When the Daemon auto-restarts, I can hear a few more seconds of the sequence continues playback, but then it cuts out again and the playlist stops.

Notes:
I can play the sequence directly on 9.1 (via a playlist that does not use Dynamic) and it plays fine.  So I know the sequence is OK.

I have been using Dynamic playlists on various versions of FPP <=6.1.1 and it worked fine.  On 6.1.1 during playback, the sequence plays fine, the status screen shows the sequence & media, time elapsed & countdown, etc.  On 9.1, it doesn't show the time elapsed & countdown and the Daemon crashes a few seconds into playback.

I created the same dynamic playlist on 6.1.1 and its plays the sequence just fine, so I know the issue is possibly a bug with 9.1.

Attached is the crash log, JSON file that Dynamic is loading, and screenshots when both working under 6.1.1 and not working with 9.1.  Also attached is a FPP backup of my configuration.  Below is a Google Drive link to the sequence and media if you want to reproduce this yourself.  The name of the playlist in question is "test-dynamic".  The URL of "https://itwinkle.org/control-lights/test.json" is live and accessible, if needed.

https://drive.google.com/file/d/13Xd9znA-eZrIj3hGNhvzOBhbldcneSve/view?usp=sharing

Thanks for looking into this, I appreciate it!  Please let me know if you need more information.

**Comment by tomhammond** [comment]
The reason why I upgraded from 6.1.1 to 9.1 was to improve Twinkly
support.  One idea I can try is downgrade FPP to the version with the most
recent Twinkly fix, then see if the Dynamic  playlist entry is broken or
not.  I think FPP 7.5 has the most recent Twinkly fix.  Do you want me to
install 7.5 and see if the Dynamic playlist works?

**Comment by dkulp** [comment]
I believe this is now fixed on master if you just want to flip from 9.1 to master branch and give that a test.

**Comment by tomhammond** [comment]
I flipped to master branch, rebooted FPP, but the daemon still crashes when using the Dynamic playlist entry.

**Comment by tomhammond** [comment]
I started testing older versions of FPP.  So far, Dynamic works on versions 8.3 and below.  I will test versions 8.4-9.0 early in the week.

One thing I noticed, after imaging FPP then restoring settings (which includes playlists), my custom dynamic playlist (from FPP 6.1.1) crashes the daemon, but if I recreate a fresh playlist with the same entries, the dynamic playlist works fine (on FPP 8.3 and below).  Regardless, recreating a fresh playlist on 9.1 does not help (daemon still crashes).

I'll provide more version checking soon.

**Comment by tomhammond** [comment]
Dynamic doesn't work in FPP 8.4 & 8.5, so the bug was introduced in 8.4.  I reimaged a fresh 8.3 a second time and verified that Dynamic works fine.  In 8.4 and higher the UI messes up in the "Main Playlist area" as it adveanced through the playlist steps and the daemon crashes. 

I used my regular Dynamic play list for testing, not the "test" one.  It works fine in 8.3:

![Image](https://github.com/user-attachments/assets/36f701e9-9200-47d0-a52a-0442eba6f880)

**Comment by dkulp** [comment]
Thanks.   That definitely helped.   Can you flip back to master branch (from 9.1) and retest?  I just put in place some guard checks to hopefully prevent the crashes.    I'd like to know if that allows it to then work.

**Comment by tomhammond** [comment]
I did a fresh image of 9.1 and changed to master.  It compiled, but not sure if it finished?  See screenshot.  After waiting at that screen a long time, I hard reset the Pi and it booted into the master version of FPP.  Is this normal?

<img width="1755" height="1813" alt="Image" src="https://github.com/user-attachments/assets/2919006f-9717-453d-af5a-161dfb40c693" />

---

FPP works better; the UI advances through the playlist entries and the Dynamic entry plays the sequence defined by the URL.  However, it shows "Playing - 'undefined'/'undefined'" for the Player Status during the Dynamic entry and does not show its elapsed time (it shows the previous entry's elapsed time (frozen) and does not update).

<img width="2589" height="1813" alt="Image" src="https://github.com/user-attachments/assets/44657064-e2e1-4cb0-8207-67b0dc779834" />

---

I also found another bug.  If I create a playlist with the same name as an existing playlist, it does not warn me of the previous playlist.  It then wipes out the previous playlist and create an empty one, even though I did not click Save Playlist.  

I also noticed the UI freeze after trying to create a playlist with the same name as a previous playlist; the Add Playlist button darkened after clicked but the UI froze, forcing me to hard reset the Pi.

<img width="2589" height="1813" alt="Image" src="https://github.com/user-attachments/assets/8f31a0bf-30e2-40e8-80d4-db8f18957694" />

**Comment by darylc** [comment]
@tomhammond Thanks for the update, let us know when you work out which version it got broken in.

**Comment by OnlineDynamic** [comment]
Is it crashing on master branch though, post my changes?
