### ISSUE TITLE
Docker update to 9.4 `Waiting 1765416816,auto seconds`

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#2483]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP docker `fpp:latest` 9.4 73800dca2

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Update 3 x K4-PB PB2's from 9.3 to 9.4
2. Notice that even after pulling `latest` the docker instance also wanted to update to 9.4, ok, let's see what happens.
3. After update asks to reboot.
4. After reboot: `Boot delay in progress: Waiting 1765416816,auto seconds before starting FPPD`

**Expected behavior**: 
`latest` is already 9.4, or updating to 9.4 on docker does not result in waiting for ~56 years.

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

Trying to pull logs:

```logs
Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, bool given in /opt/fpp/www/common.php:69 Stack trace: #0 /opt/fpp/www/api/controllers/files.php(705): ScrubFile() #1 /opt/fpp/www/api/controllers/files.php(614): ZipConfigs() #2 /opt/fpp/www/api/controllers/files.php(580): ZipLogs() #3 /opt/fpp/www/api/lib/limonade.php(430): GetZipDir() #4 /opt/fpp/www/api/index.php(194): run() #5 {main} thrown in /opt/fpp/www/common.php on line 69
```

<img width="2770" height="1222" alt="Image" src="https://github.com/user-attachments/assets/7e1ababb-6689-4c40-a2f0-ecf50d7b2d73" />

P.s., I know docker is not supported.

**Comment by OnlineDynamic** [comment]
Thanks for highlighting - this is actually just a bug in the warning, the boot delay isn't really taking 56 years, if you have it set to auto its waiting for a network connection.  I have fixed message on master branch

**Comment by ptr727** [comment]
Log zip now works.

Boot delay still does not work:

<img width="2729" height="1085" alt="Image" src="https://github.com/user-attachments/assets/7850402d-3073-4f44-a7e2-373b4e7e008c" />

**Comment by OnlineDynamic** [comment]
think Chris has resolved this in commit: https://github.com/FalconChristmas/fpp/commit/63607331bb2e7090f351277206ca53d0bc11438f

**Comment by skyblaster** [comment]
I ran the image from Docker Hub (docker.io/falconchristmas/fpp:9.5.2)
