### ISSUE TITLE
Video flashes white/grey at end of some videos - already have solution

### ISSUE THREAD

**Issue by gerryhernandez** [FalconChristmas/fpp#478]
Hey everyone. I'm posting this as an issue so that if you're facing the same problem, you can at least find some instructions as a manual fix for the time being. I'd be happy to contribute a fix to the repo, but I don't immediately have the time. But give me a couple weeks when things settle down for me and I'd gladly put it together.

Root cause: The OMXPlayer binary that's used in mainline FPP distribution is old and does not have newer fixes. These newer fixes affect the way the decode queue is handled, among other things. The white/grey "flash" at the end of videos that many of us have been experiencing have been fixed with these changes.

Manual fix:
1. Update Raspberry Pi firmware via `sudo rpi-update`. The new firmware is required to build due to a dependency on updated headers.
2. Step 1 will require a reboot.
3. Essentially emulate FPP_Install.sh by doing the following:
```
cd /opt
git clone https://github.com/popcornmix/omxplayer.git
cd omxplayer
wget -O- https://raw.githubusercontent.com/FalconChristmas/fpp/master/external/omxplayer/FPP_omxplayer.diff | patch -p1
./prepare-native-raspbian.sh
make omxplayer.bin
cp omxplayer.bin /usr/bin/omxplayer.bin
```

For a permanent fix, we'd need to discuss how we'd want to deal with the firmware. I don't believe FPP already has a mechanism for performing a reboot in the middle of an upgrade, so that may be a prerequisite feature before implementing this in a polished way. Correct me if I'm wrong, though.

A semi-permanent fix would be to test an OMXPlayer binary built with the latest code on an older, non-firmware-updated FPP OS image. If everything works, this is a pretty decent transition for most people and it can be distributed via a standard update script.

**Comment by dkulp** [comment]
Running rpi-update to update to experimental kernels and libraries is not something I'd want to do at this point.   The RPI folks don't recommend ever running that.  My gut feeling is that this is something that needs to wait until it's available in a dist-upgrade or more likely when we can flip to buster next year.

**Comment by gerryhernandez** [comment]
Makes sense. Would you like me to push the updated OMXPlayer binary into another `fpp-binaries` branch for testing, or just revisit this in 2019? Unfortunately, I don't have an extra Pi or SD card that *isn't* running my show right now, so I can't readily test it on the current stable release. But it does look like this bug isn't really affecting too many people, so I'm leaning toward "do nothing." ;)

**Comment by cpinkham** [comment]
Is this fixed in the Buster FPP v3.5.x SD image?

**Comment by cpinkham** [comment]
FPP v4.x will no longer use omxplayer for playing video, Dan wrote a new video player using libVLC that still takes advantage of the hardware decoding available on the Pi.  Can you please test with the latest FPP v4.x Alpha images and confirm if this is no longer an issue in the new code?

**Comment by KuhnDaniel** [comment]
Hello Chris, Version: v4.x-master-362-g85aa2d29 (master branch) 
I still have the problem that no videos can be played via HDMI. I only get the soundtrack but no picture ?! RPI3 and RPI4. Do you have any idea?

**Comment by patdelaney** [comment]
Chris I am not seeing this on Pi V4 running master on the

v4.0-beta1 disk image.  But I am seeing random out of sync issues.

**Comment by KuhnDaniel** [comment]
News. I am create a new SD with the last v4.x-master-218-gc31246a0 (master branch) and :-)
it works, greate :-) before I always worked with updates ?!
Thanks

**Comment by cpinkham** [comment]
FPP doesn't use omxplayer anymore, we have a new built-in player using libvlc.  Closing ticket.
