### ISSUE TITLE
FPP4.0 wont start fppd if mqtt host not found.  No error displayed

### ISSUE THREAD

**Issue by thedannymullen** [FalconChristmas/fpp#738]
Recently, I changed some dns settings on my network.  I did not realize that FPP did not have the fqdn for my mqtt host.  That said the fppd would not start.  I examined the logs and found this:

2020-06-08 10:51:38.656 (2167) log.c:231: =========================================
2020-06-08 10:51:38.667 (2167) mqtt.cpp:185: Using MQTT client id of FPP_1712 
2020-06-08 10:51:38.667 (2167) mqtt.cpp:209: No CA File specified for MQTT
2020-06-08 10:52:34.723 (2167) mqtt.cpp:218: Error, unable to connect to Mosquitto Broker at treasurebox: 15
2020-06-08 10:52:34.724 (2167) mqtt.cpp:219: MQTT Error: Block device required
2020-06-08 10:52:35.636 (2205) log.c:228: =========================================
2020-06-08 10:52:35.637 (2205) log.c:229: FPP 4.x-master-331-gbb97616c
2020-06-08 10:52:35.637 (2205) log.c:230: Branch: master
2020-06-08 10:52:35.637 (2205) log.c:231: =========================================

Issue was resolved by adding the fqdn to my mqtt host.  The question, is this something that should happen and/or should we maybe display some type of error besides buried in the logs.  Something similiar to when controllers are not pingable, could we maybe say mqtt host unreachable?  

I am ok either way, and I am up and running.  Thinking I would offer a suggestion for improvement possibly, let me know your thoughts.

**Comment by ghormann** [comment]
You are using Master from May 13.  On May 15, I committed d368c765d1a409b8e13c5fafbd12a60bbf50afdf to address this problem. 

Can you upgrade to the latest and see if it addresses the problem?  In this newer version, fppd should start and you should also see MQTT status listed on the main screen (if MQTT is configured) 
![image](https://user-images.githubusercontent.com/24968726/84091478-7cc11680-a9c2-11ea-8334-72212c313162.png)

**Comment by thedannymullen** [comment]
Thanks I have updated, I will test when on my laptop to verify then close the issue.

**Comment by thedannymullen** [comment]
I now have the most recent update from what I can see: 


Local Git Version: | 8736fbe ChangeLog
-- | --
Remote Git Version: | 8736fbe

Seems the isxue still exists, if the mqtt hostname incorrect fppd won't start.

**Comment by ghormann** [comment]
Ok, I will try and reproduce.   I notice there was a change after my commit to fix this issue.

**Comment by ghormann** [comment]
@thedannymullen  I believe this should fix your issue.   The issue I fixed previously is if a firewall blocked the connect, but if the DNS lookup fails it would fail differently.  Now, it just logs a message and continues to boot fppd.

@cpinkham  I once again changed the way HandleConnect() is called.   I know you added back with 77fc0ec94b168d71ce569003b16dbd7853fedb6d the need to call HandleConnect() in setReady().   I understand the reasoning from your commit message, but it can also cause a problem with making FPP think MQTT is connected when it isn't actually connected.  To avoid this, I changed setReady() to only call HandleConnect() if, mqtt is already connected.  I think this is safe.  If MQTT is connected, then the new subscriptions will be added.  If the connection process hasn't finished yet, then when MQTT does actually connect, all of the pending subscriptions will occur.    I've tested this on my machine and it seems to work fine.   I also ask that you test given you've seen the problem before.

**Comment by thedannymullen** [comment]
Looks like it is working with this version: Version: v4.x-master-397-ge355b77f (master branch)

I like that it says the mqtt status also on the status page.  

@ghormann thanks so much!

**Comment by cpinkham** [comment]
@ghormann I think this newer code is working for my test case as well.  I can see the Home Assistant plugin sending messages out after connection when previously it would fail until I put in the setReady/HandleConnect change.

**Comment by ghormann** [comment]
Thanks for confirming @cpinkham !
