### ISSUE TITLE
Remote video playback freezes but audio continues to play through hdmi

### ISSUE THREAD

**Issue by MarkA75160** [FalconChristmas/fpp#883]
**FPP Version and Hardware**: 

FPP Version:	v4.x-master-651-gffa069af
Platform:	Raspberry Pi (Pi 4)
FPP OS Build:	v4.4
OS Version:	Raspbian GNU/Linux 10 (buster)
Hardware Serial Number:	1000000060dc1c72
Kernel Version:	5.4.72-v7l+

**Describe the bug and Steps to reproduce**: 

FPP Remote setup to play .mp4 videos in sync with Master playing .mp3 audio file.
Video player attempts to stay in sync via speedup/slowdown playback.  However if it gets far enough off it then attempts to jump forward or back.  After a few attempts (uncertain how far off or how many jumps) the remote video playback freezes but the remote audio continues to play through the HDMI port

**Expected behavior**: 
The video playback should continue attempting to stay in sync throughout the duration of the entire song without freezing.

**Additional context**: 
This has been seen on many different video files so its not specific to any one video.

When the sequence ends, the "stuck" video will terminate and the next sequence video will start normally, but also may freeze up depending on how far off the sync gets.

If the "Ignore Media Sync" option is selected, the videos will play to completion without freezing, but they will not be in sync with the Master (and the drift or skew between the two players is very noticeable).

In the attached log files, the "freeze" happened at 12:35:54 - at this point, "Stop Gracefully" was selected.
The next entry is 12:36:28 which is 34 seconds later when the sequence ended
In this log, the remaining sequences were the Lead-out portion which are very short and did not freeze before completion.
[FPP_Logs_20201127.1856.zip](https://github.com/FalconChristmas/fpp/files/5609322/FPP_Logs_20201127.1856.zip)

**Additional Attachments**
[FPP_Logs_20201127.1856.zip](https://github.com/FalconChristmas/fpp/files/5609322/FPP_Logs_20201127.1856.zip)

**Comment by cpinkham** [comment]
Believe this was fixed in master by d285d319b58.

**Comment by vvvteddybearvvv** [comment]
this is still not fixed..




2020-12-16 03:39:38.266 (5647) fseq/FSEQFile.cpp:358: Sequence File Information
2020-12-16 03:39:38.267 (5647) fseq/FSEQFile.cpp:359: seqFilename          : /home/fpp/media/sequences/lastchristmasmix.fseq
2020-12-16 03:39:38.267 (5647) fseq/FSEQFile.cpp:360: seqVersion            : 2.0
2020-12-16 03:39:38.267 (5647) fseq/FSEQFile.cpp:361: seqChanDataOffset    : 2037
2020-12-16 03:39:38.267 (5647) fseq/FSEQFile.cpp:362: seqChannelCount      : 104040
2020-12-16 03:39:38.268 (5647) fseq/FSEQFile.cpp:363: seqNumPeriods        : 2941
2020-12-16 03:39:38.268 (5647) fseq/FSEQFile.cpp:364: seqStepTime          : 50ms
2020-12-16 03:39:38.268 (5647) fseq/FSEQFile.cpp:1711: Sequence File Information
2020-12-16 03:39:38.269 (5647) fseq/FSEQFile.cpp:1712: compressionType      : 0
2020-12-16 03:39:38.270 (5647) fseq/FSEQFile.cpp:1713: numBlocks            : 0
2020-12-16 03:39:38.270 (5647) fseq/FSEQFile.cpp:1718: numRanges            : 0
2020-12-16 03:39:38.271 (5647) channeloutput/channeloutputthread.c:311: StartChannelOutputThread()
2020-12-16 03:39:38.271 (5647) channeloutput/channeloutputthread.c:330: Channel Output thread is already running
2020-12-16 03:39:38.272 (5647) Sequence.cpp:332: seqRefreshRate        : 20.000000
2020-12-16 03:39:38.272 (5647) Sequence.cpp:333: seqMSDuration        : 147050
2020-12-16 03:39:38.272 (5647) Sequence.cpp:334: seqMSRemaining        : 147050
2020-12-16 03:39:38.273 (5647) MultiSync.cpp:2268: ProcessSyncPacket()  filename: lastchristmasmix.fseq    type: 0  filetype: 0  frameNumber: 0  secondsElapsed: 0.00
2020-12-16 03:39:38.273 (5647) MultiSync.cpp:2117: StartSyncedSequence(lastchristmasmix.fseq)
2020-12-16 03:39:38.274 (5647) channeloutput/channeloutputthread.c:311: StartChannelOutputThread()
2020-12-16 03:39:38.274 (5647) channeloutput/channeloutputthread.c:330: Channel Output thread is already running
2020-12-16 03:39:38.274 (5647) MultiSync.cpp:2268: ProcessSyncPacket()  filename: lastchristmasmix.mp3    type: 0  filetype: 1  frameNumber: 0  secondsElapsed: 0.00
2020-12-16 03:39:38.275 (5647) MultiSync.cpp:2218: StartSyncedMedia(lastchristmasmix.mp3)
2020-12-16 03:39:38.275 (5647) mediaoutput/VLCOut.cpp:249: VLCOutput::Start() 1B40DB0
2020-12-16 03:39:38.276 (5647) MultiSync.cpp:2268: ProcessSyncPacket()  filename: lastchristmasmix.fseq    type: 2  filetype: 0  frameNumber: 0  secondsElapsed: 0.03
2020-12-16 03:39:38.277 (5669) channeloutput/channeloutputthread.c:246: Output Thread: Loop: 50000us, Send: 6037us, Read: 22us, Process: 13us, Sleep: 43928us, FrameNum: 1
2020-12-16 03:39:38.285 (5798) mediaoutput/VLCOut.cpp:90: unknown box type titl (incompletely loaded)
2020-12-16 03:39:38.287 (5798) mediaoutput/VLCOut.cpp:90: elst box found
2020-12-16 03:39:38.291 (5798) mediaoutput/VLCOut.cpp:90: STTS table of 1 entries
2020-12-16 03:39:38.301 (5798) mediaoutput/VLCOut.cpp:90: elst box found
2020-12-16 03:39:38.305 (5798) mediaoutput/VLCOut.cpp:90: STTS table of 1 entries
2020-12-16 03:39:38.343 (5805) mediaoutput/VLCOut.cpp:90: device cannot be paused
2020-12-16 03:39:38.350 (5799) mediaoutput/VLCOut.cpp:90: VCSM init succeeded: Legacy
2020-12-16 03:39:38.353 (5799) mediaoutput/VLCOut.cpp:90: VCSM init succeeded: Legacy
2020-12-16 03:39:38.369 (5647) MultiSync.cpp:2268: ProcessSyncPacket()  filename: lastchristmasmix.fseq    type: 2  filetype: 0  frameNumber: 4  secondsElapsed: 0.22
2020-12-16 03:39:38.371 (5647) channeloutput/channeloutputthread.c:510: LightDelay: 50000, newLightDelay: 49000,  DiffFrames: -2    2/4
2020-12-16 03:39:38.571 (5647) MultiSync.cpp:2268: ProcessSyncPacket()  filename: lastchristmasmix.fseq    type: 2  filetype: 0  frameNumber: 8  secondsElapsed: 0.44
2020-12-16 03:39:38.571 (5647) channeloutput/channeloutputthread.c:510: LightDelay: 49000, newLightDelay: 48000,  DiffFrames: -2    6/8
2020-12-16 03:39:38.630 (5647) MultiSync.cpp:2268: ProcessSyncPacket()  filename: lastchristmasmix.mp3    type: 2  filetype: 1  frameNumber: 0  secondsElapsed: 0.50
2020-12-16 03:39:38.687 (5812) mediaoutput/VLCOut.cpp:90: picture is too late to be displayed (missing 185 ms)
2020-12-16 03:39:38.749 (5812) mediaoutput/VLCOut.cpp:90: picture is too late to be displayed (missing 159 ms)
2020-12-16 03:39:38.769 (5647) MultiSync.cpp:2268: ProcessSyncPacket()  filename: lastchristmasmix.fseq    type: 2  filetype: 0  frameNumber: 12  secondsElapsed: 0.63
2020-12-16 03:39:38.787 (5812) mediaoutput/VLCOut.cpp:90: picture is too late to be displayed (missing 118 ms)
2020-12-16 03:39:38.839 (5812) mediaoutput/VLCOut.cpp:90: picture is too late to be displayed (missing 77 ms)
2020-12-16 03:39:38.917 (5812) mediaoutput/VLCOut.cpp:90: picture is too late to be displayed (missing 86 ms)
2020-12-16 03:39:38.949 (5812) mediaoutput/VLCOut.cpp:90: picture is too late to be displayed (missing 79 ms)
2020-12-16 03:39:38.970 (5647) MultiSync.cpp:2268: ProcessSyncPacket()  filename: lastchristmasmix.fseq    type: 2  filetype: 0  frameNumber: 16  secondsElapsed: 0.82
2020-12-16 03:39:39.001 (5812) mediaoutput/VLCOut.cpp:90: picture is too late to be displayed (missing 66 ms)
2020-12-16 03:39:39.040 (5803) fppd.c:225: Crash handler called:  11
2020-12-16 03:39:39.143 (5647) MultiSync.cpp:2268: ProcessSyncPacket()  filename: lastchristmasmix.mp3    type: 2  filetype: 1  frameNumber: 0  secondsElapsed: 1.01
2020-12-16 03:39:39.145 (5647) mediaoutput/VLCOut.cpp:471: Diff: -640  RateDiff: -12.800 / 0  New rate: 1.018/1.000  Calc Rate: 1.100
2020-12-16 03:39:39.145 (5647) mediaoutput/VLCOut.cpp:473: Calling libvlc_media_player_set_rate(1.018293)
2020-12-16 03:39:39.170 (5647) MultiSync.cpp:2268: ProcessSyncPacket()  filename: lastchristmasmix.fseq    type: 2  filetype: 0  frameNumber: 20  secondsElapsed: 1.03
2020-12-16 03:39:39.297 (5669) channeloutput/channeloutputthread.c:246: Output Thread: Loop: 48000us, Send: 17us, Read: 58us, Process: 9us, Sleep: 47916us, FrameNum: 22
2020-12-16 03:39:39.370 (5647) MultiSync.cpp:2268: ProcessSyncPacket()  filename: lastchristmasmix.fseq    type: 2  filetype: 0  frameNumber: 24  secondsElapsed: 1.23
2020-12-16 03:39:39.570 (5647) MultiSync.cpp:2268: ProcessSyncPacket()  filename: lastchristmasmix.fseq    type: 2  filetype: 0  frameNumber: 28  secondsElapsed: 1.44
